package com.example.aquasmart10

object Routes {
    var BerandaActivity = "Beranda_Activity"
    var KelolaActivity = "Kelola_Activity"
    var KelolaPakanActivity = "Kelola_Pakan"
    var StokIkanActivity = "Stok_ikan"
    var OverviewStokIkan = "Overview_StokIkan"
    var TambahIkanActivity = "TambahStok_Ikan"
    var EditIkanActivity = "EditStok_Ikan"
    var KematianIkanActivity = "Kematian_Ikan"
    var TambahKematianIkanActivity = "Tambah_Kematian"
    var EditKematianIkanActivity = "Edit_Kematian"
    var NotifikasiActivity = "Notif"
    var PengingatPanenActivity = "Pengingat_Panen"
    var EditJadwalPanenActivity = "EditPengingat_Panen"
    var TambahJadwalPanenActivity = "TambahPengingat_Panen"
    var HitungDosisPakanActivity = "Hitung_Dosis"
    var ProfileAwalActivity = "Profile_Awal"
    var OverviewProfileActivity = "Overview_Profile"
    var EditProfileActivity = "Edit_Profile"
    var KolamIkanScreen = "Kolam_Body"
    var TambahKolamScreen = "Tambah_Kolam"
    var EditKolamScreen = "Edit_Kolam"
    var StokPakanActivity = "Stok_Pakan"
    var EditPakanScreen = "Edit_Pakan"
    var TambahPakanScreen = "Tambah_Pakan"
    var JadwalPakanScreen = "Jadwal_Pakan"
    var PengingatPakanActivity = "Pengingat_Pakan"
    var EditJadwalPakanActivity = "Edit_JadwalPakan"
    var TambahJadwalPakanActivity = "Tambah_JadwalPakan"
    var LoginScreen = "Login_Page"
}